### ISSUE TITLE
Accepting Hacktoberfest 2021 pull requests 

### ISSUE THREAD

**Issue by its-Kumar** [its-Kumar/Data_Structure_and_Algorithm#2]
Feel free to contribute 🙂

**Comment by Azmeerabhagyasree** [comment]
i would like to contribute

**Comment by its-Kumar** [comment]
> i would like to contribute

Please contribute and send pull request 

Happy Hacking!

**Comment by Rohit2001Das** [comment]
I would like to contribute in this.

**Comment by its-Kumar** [comment]
@Rohit2001Das 
Please send PR

**Comment by shaurya5** [comment]
I would like to contribute

**Comment by its-Kumar** [comment]
> I would like to contribute

Please go ahead

**Comment by shikhar13012001** [comment]
I would like to contribute

**Comment by KIRTIKUMARKK21** [comment]
I would like to contribute

**Comment by its-Kumar** [comment]
@shikhar13012001 @KIRTIKUMARKK21 please contribute and send pull request

**Comment by nkhandelwal07** [comment]
What needs to be contributed?

**Comment by Azmeerabhagyasree** [comment]
i have send the PR request

**Comment by SakshiJoshi26** [comment]
I would like to contribute to this.

**Comment by its-Kumar** [comment]
> I would like to contribute to this.

Please send Pull request

**Comment by radha919** [comment]
@its-Kumar  please review my PR #34

**Comment by its-Kumar** [comment]
> I would like to contribute.

Please

**Comment by its-Kumar** [comment]
Thank you everyone,
for your contributions 👍🏼
